yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<str:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
]
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied_view'
handler500 = 'core.views.server_error'
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
import textwrap as tw

from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    """ Модель для сообществ """
    title = models.CharField('Заголовок', max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField('Описание')

    class Meta:
        verbose_name = "Group"

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    """ Модель для хранения постов """
    text = models.TextField('Текст поста')
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='groups_posts',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        verbose_name = "Post"
        ordering = ('-pub_date', 'pk')

    def __str__(self) -> str:
        return tw.shorten(str(self.text), 15)


class Comment(models.Model):
    """ Модель для хранения комментариев """
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField('Текст комментария')
    created = models.DateTimeField('Дата публикации комментария',
                                   auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )

    class Meta:
        verbose_name = "Comment"

    def __str__(self) -> str:
        return tw.shorten(str(self.text), 30)


class Follow(models.Model):
    """ Модель для хранения подписок """
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        # сделал проверку, но еще есть проверка во вью
        constraints = [
            models.UniqueConstraint(
                fields=('user', 'author'),
                name='unique_list'
            )
        ]

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        help_texts = {
            'text': ('Текст нового поста'),
            'group': ('Группа, к которой будет относиться пост'),
            'image': ('Фото или картинка для поста')
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        help_texts = {
            'text': ('Текст нового комментария')
        }

yatube/posts/views.py
from django.conf import settings
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .forms import PostForm, CommentForm
from .models import Post, Group, User, Comment, Follow


def authorized_only(func):
    # Декоратор для проверки авторизован ли пользователь
    def check_user(request, *args, **kwargs):
        if request.user.is_authenticated:
            return func(request, *args, **kwargs)
        return redirect('/auth/login/')

    return check_user


def index(request: HttpRequest) -> HttpResponse:
    post_list = Post.objects.all()
    paginator = Paginator(post_list, settings.PER_PAGE_PAGINATOR)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    title = 'Последние обновления на сайте'
    context = {
        'page_obj': page_obj,
        'title': title,
    }
    template_name = 'posts/index.html'
    return render(request, template_name, context)


def group_posts(request: HttpRequest, slug: str) -> HttpResponse:
    group = get_object_or_404(Group, slug=slug)
    posts = group.groups_posts.all()
    paginator = Paginator(posts, settings.PER_PAGE_PAGINATOR)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'slug': slug,
        'group': group,
        'posts': posts,
        'page_obj': page_obj,
    }
    template_name = 'posts/group_list.html'
    return render(request, template_name, context=context)


def profile(request: HttpRequest, username: str) -> HttpResponse:
    username = get_object_or_404(User, username=username)
    post_list = username.posts.all()
    following = username.following.exists()
    paginator = Paginator(post_list, settings.PER_PAGE_PAGINATOR)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'username': username,
        'post_list': post_list,
        'page_obj': page_obj,
        'following': following,
    }
    template_name = 'posts/profile.html'
    return render(request, template_name, context=context)


def post_detail(request: HttpRequest, post_id: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=post_id)
    post_text = get_object_or_404(Post, id=post_id).text[:30]
    comments = Comment.objects.filter(post_id=post_id)
    form = CommentForm()
    context = {
        'post': post,
        'post_text': post_text,
        'comments': comments,
        'form': form,
    }
    template_name = 'posts/post_detail.html'
    return render(request, template_name, context)


@authorized_only
def post_create(request: HttpRequest) -> HttpResponse:
    is_edit = False
    title = 'Добавить запись'
    form = PostForm(request.POST or None,
                    files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.pub_date = timezone.now()
        post.save()
        return redirect('posts:profile', username=post.author.username)
    context = {
        'form': form,
        'is_edit': is_edit,
        'title': title,
    }
    template_name = 'posts/create_post.html'
    return render(request, template_name, context)


@authorized_only
def post_edit(request: HttpRequest, post_id: int) -> HttpResponse:
    post = get_object_or_404(Post, id=post_id)
    author = post.author.username
    group = post.group
    is_edit = True
    title = 'Редактировать запись'
    if request.user.username == author:
        if request.method == "POST":
            form = PostForm(request.POST or None,
                            files=request.FILES or None,
                            instance=post)
            if form.is_valid():
                post = form.save(commit=False)
                post.author = request.user
                post.pub_date = timezone.now()
                post.save()
                return redirect('posts:post_detail', post_id=post.pk)
        else:
            form = PostForm(instance=post)
        context = {
            'form': form,
            'group': group,
            'is_edit': is_edit,
            'title': title,
        }
        template_name = 'posts/create_post.html'
        return render(request, template_name, context)
    else:
        template_name = 'posts:post_detail'
        return redirect(template_name, post_id=post.pk)


@authorized_only
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@authorized_only
def follow_index(request: HttpRequest) -> HttpResponse:
    user = request.user
    authors = user.follower.values_list('author', flat=True)
    post_list = Post.objects.filter(author__id__in=authors)
    paginator = Paginator(post_list, settings.PER_PAGE_PAGINATOR)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    title = 'Посты авторов, на которых вы подписаны'
    context = {
        'page_obj': page_obj,
        'title': title,
    }
    template_name = 'posts/follow.html'
    return render(request, template_name, context)


@authorized_only
def profile_follow(request, username):
    author = User.objects.get(username=username)
    user = request.user
    if author != user and (author.following.count() == 0):
        Follow.objects.create(user=user, author=author)
    return redirect('posts:profile', username=username)


@authorized_only
def profile_unfollow(request, username):
    user = request.user
    Follow.objects.get(user=user, author__username=username).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/add_comment.html
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text }}
        </p>
      </div>
    </div>
{% endfor %}

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-6 p-5">
            <div class="card">
                <div class="card-header">
                    {{ title }}
                </div>
                <div class="card-body">
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    {{ error|escape }}
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                {{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endif %}

                    <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create' %}">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group row my-3 p-3">
                                <label for="{{ field.id_for_label }}">
                                    {{ field.label }}
                                    {% if field.field.required %}
                                        <span class="required text-danger">*</span>
                                    {% endif %}
                                </label>
                                {{ field }}
                                {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                        {{ field.help_text|safe }}
                                    </small>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <div class="col-md-6 offset-md-10">
                            <button type="submit" class="btn btn-primary">
                                {% if is_edit %}
                                    Сохранить
                                {% else %}
                                    Добавить
                                {% endif %}
                            </button>
                        </div>
                    </form>
                </div> <!-- card body -->
            </div> <!-- card -->
        </div> <!-- col -->
    </div> <!-- row -->
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% load cache %}
{% block title %}
    {{ title|safe }}
{% endblock %}
{% block content %}
    {% cache 20 index_page %}
        <div class="container">
        <h1>{{ title|safe }}</h1>
        {% include 'posts/includes/switcher.html' %}
        <article>
        {% for post in page_obj %}
            <ul>
                <li>
                    Автор: {{ post.author.get_full_name }}
                    <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
                </li>
                <li>
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
            </ul>
            <p>{{ post.text }}</p>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
            {% if post.group.slug %}
                <br>
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
            {% if not forloop.last %}
                <hr>
            {% endif %}
        {% endfor %}
    {% endcache %}
{% include 'posts/includes/paginator.html' %}
</article>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}
    Записи сообщества {{ group.title }}
{% endblock %}
{% block content %}
    <div class="container">
        {% block header %}
            <h1>{{ group.title }}</h1>
            <p>{{ group.description }}</p>
        {% endblock %}
        <article>
            {% for post in posts %}
                <ul>
                    <li>
                        Автор: {{ post.author.get_full_name }}
                    </li>
                    <li>
                        Дата публикации: {{ post.pub_date|date:"d E Y" }}
                    </li>
                </ul>
                <p>{{ post.text }}</p>
                {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                    <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
                {% if not forloop.last %}
                    <hr>
                {% endif %}
            {% endfor %}
            {% include 'posts/includes/paginator.html' %}
        </article>
    </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% load cache %}
{% block title %}
    {{ title|safe }}
{% endblock %}
{% block content %}
    {% cache 20 index_page %}
        <div class="container">
        <h1>{{ title|safe }}</h1>
        {% include 'posts/includes/switcher.html' %}
        <article>
        {% for post in page_obj %}
            <ul>
                <li>
                    Автор: {{ post.author.get_full_name }}
                    <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
                </li>
                <li>
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
            </ul>
            <p>{{ post.text }}</p>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
            {% if post.group.slug %}
                <br>
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
            {% if not forloop.last %}
                <hr>
            {% endif %}
        {% endfor %}
    {% endcache %}
{% include 'posts/includes/paginator.html' %}
</article>
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}

{% block title %}
    Пост {{ post_text }}
{% endblock %}

{% block content %}
    <div class="row">
        <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
                {% if post.group %}
                    <li class="list-group-item">
                        Группа: {{ post.group.title }}
                        <a href="{% url 'posts:group_list' post.group.slug %}">
                            все записи группы
                        </a>
                    </li>
                {% endif %}
                <li class="list-group-item">
                    Автор: {{ post.author }}
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Всего постов автора: <span>{{ post.author.posts.count }}</span>
                </li>
                <li class="list-group-item">
                    <a href="{% url 'posts:profile' post.author %}">
                        все посты пользователя
                    </a>
                </li>
            </ul>
        </aside>
        <article class="col-12 col-md-9">
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>
                {{ post_text }}
            </p>
            {% if post.author.username == user.username %}
                <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
                    редактировать запись
                </a>
            {% endif %}

            {% load user_filters %}

            {% if user.is_authenticated %}
                <div class="card my-4">
                    <h5 class="card-header">Добавить комментарий:</h5>
                    <div class="card-body">
                        <form method="post" action="{% url 'posts:add_comment' post.id %}">
                            {% csrf_token %}
                            <div class="form-group mb-2">
                                {{ form.text|addclass:"form-control" }}
                            </div>
                            <button type="submit" class="btn btn-primary">Отправить</button>
                        </form>
                    </div>
                </div>
            {% endif %}

            {% for comment in comments %}
                <div class="media mb-4">
                    <div class="media-body">
                        <h5 class="mt-0">
                            <a href="{% url 'posts:profile' comment.author.username %}">
                                {{ comment.author.username }}
                            </a>
                        </h5>
                        <p>
                            {{ comment.text }}
                        </p>
                    </div>
                </div>
            {% endfor %}
        </article>
    </div>

{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}
    Профайл пользователя {{ username }}
{% endblock %}
{% block content %}
    <div class="container py-5">
        <h1>Все посты пользователя {{ username }} </h1>
        <h3>Всего постов: {{ username.posts.count }} </h3>
        {% if following %}
            <a
                    class="btn btn-lg btn-light"
                    href="{% url 'posts:profile_unfollow' username %}" role="button"
            >
                Отписаться
            </a>
        {% else %}
            <a
                    class="btn btn-lg btn-primary"
                    href="{% url 'posts:profile_follow' username %}" role="button"
            >
                Подписаться
            </a>
        {% endif %}
        <article>
            {% for post in page_obj %}
                <ul>
                    <li>
                        Автор: {{ post.author.get_full_name }}
                        <a href="{% url 'posts:profile' username %}">все посты пользователя</a>
                    </li>
                    <li>
                        Дата публикации: {{ post.pub_date|date:"d E Y" }}
                    </li>
                </ul>
                <p>
                    {{ post.text }}
                </p>
                {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                    <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
                <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
                </article>
                {% if post.group %}
                    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
                {% endif %}
                <!-- Остальные посты. после последнего нет черты -->
                {% if not forloop.last %}
                    <hr>{% endif %}
            {% endfor %}
        {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock %}